In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age':  [25, 30, 35],
    'score': [88.5, 92.0, 78.3]
})
print(df)

      name  age  score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   35   78.3

In [8]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'], name='scores')
print(s)

print(s['b'])  # 20

a    10
b    20
c    30
Name: scores, dtype: int64
20

In [9]:
df = pd.read_csv('array.csv')
# df = pd.read_csv('array.csv', index_col=0, parse_dates=['date'])

df.to_csv('output.csv', index=False)

# df = pd.read_excel('file.xlsx', sheet_name='Sheet1')
# df = pd.read_json('array.json')
# df.to_parquet('file.parquet')

In [10]:
df.head()      
df.head(10)
df.tail(3)
df.info()
df.describe()
df.describe(include='all')  # includes non-numeric

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0.00    2 non-null      float64
 1   1.00    2 non-null      float64
 2   2.00    2 non-null      float64
 3   3.00    2 non-null      float64
dtypes: float64(4)
memory usage: 192.0 bytes

           0.00      1.00       2.00       3.00
count  2.000000  2.000000   2.000000   2.000000
mean   6.000000  7.000000   8.000000   9.000000
std    2.828427  2.828427   2.828427   2.828427
min    4.000000  5.000000   6.000000   7.000000
25%    5.000000  6.000000   7.000000   8.000000
50%    6.000000  7.000000   8.000000   9.000000
75%    7.000000  8.000000   9.000000  10.000000
max    8.000000  9.000000  10.000000  11.000000

In [11]:
print(df.shape)    # (3, 3) → rows, cols
print(df.dtypes)   # dtype per column
print(df.columns)  # Index(['name', 'age', 'score'])
print(df.index)    # RangeIndex(start=0, stop=3)
print(df.size)     # total elements = rows * cols

(2, 4)
0.00    float64
1.00    float64
2.00    float64
3.00    float64
dtype: object
Index(['0.00', '1.00', '2.00', '3.00'], dtype='object')
RangeIndex(start=0, stop=2, step=1)
8

In [12]:
df['name'].value_counts()
df['name'].value_counts(normalize=True)  # proportions
df['name'].nunique()   # number of unique values
df['name'].unique()    # array of unique values

KeyError: 'name'

In [ ]:
# Select row by index label
df.loc[0]
# Select specific rows + columns
df.loc[0:1, ['name', 'score']]
# Boolean condition
df.loc[df['age'] > 25]
# Multiple conditions
df.loc[(df['age'] > 25) & (df['score'] > 80)]

  name  age  score
1  Bob   30   92.0

In [ ]:
df.iloc[0]          # first row
df.iloc[-1]         # last row
df.iloc[0:2]        # rows 0 and 1
df.iloc[:, 1]       # second column (all rows)
df.iloc[0:2, 1:3]   # rows 0-1, cols 1-2

   age  score
0   25   88.5
1   30   92.0

In [ ]:
df.query('age > 25')
df.query('age > 25 and score >= 88')
min_age = 28
df.query('age > @min_age')   # use Python var with @
df.query('name in ["Alice", "Bob"]')

    name  age  score
0  Alice   25   88.5
1    Bob   30   92.0

In [ ]:
df = pd.DataFrame({'a': [1, np.nan, 3], 'b': [4, 5, np.nan]})

df.isnull()          # True where NaN
df.isnull().sum()    # count NaNs per column

df.dropna()          # drop rows with any NaN
df.dropna(axis=1)   # drop columns with any NaN
df.dropna(thresh=2) # keep rows with ≥2 non-NaN

df.fillna(0)                     # fill all NaN with 0
df['a'].fillna(df['a'].mean())   # fill with column mean
df.ffill()                       # forward-fill
df.bfill()                       # backward-fill

     a    b
0  1.0  4.0
1  3.0  5.0
2  3.0  NaN

In [ ]:
df.duplicated()                     # boolean mask
df.duplicated().sum()              # count duplicates

df.drop_duplicates()               # drop all dupes
df.drop_duplicates(subset=['name']) # based on column
df.drop_duplicates(keep='last')   # keep last occurrence

KeyError: Index(['name'], dtype='object')

In [ ]:
# Rename columns
df.rename(columns={'name': 'full_name', 'age': 'years'})
# Drop column(s)
df.drop(columns=['score'])
df.drop(columns='score', inplace=True)
# Drop row(s) by index
df.drop(index=[0, 2])

In [ ]:
df['age'] = df['age'].astype('float')
df['score'] = df['score'].astype('int')
df['name'] = df['name'].astype('category')  # saves memory

# Convert to datetime
df['date'] = pd.to_datetime(df['date'])
df['id']   = pd.to_numeric(df['id'], errors='coerce')

In [ ]:
df.sort_values('score')                          # ascending
df.sort_values('score', ascending=False)         # descending
df.sort_values(['age', 'score'], ascending=[True, False])

df.sort_index()           # sort by row index
df.sort_index(axis=1)     # sort columns alphabetically

In [ ]:
# Apply to a single column (Series)
df['score'].apply(lambda x: 'pass' if x >= 80 else 'fail')

# Apply to each row (axis=1)
df.apply(lambda row: row['age'] * row['score'], axis=1)

# Apply to each column (axis=0, default)
df[['age', 'score']].apply('mean')

# Named function
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())
df[['score']].apply(normalize)

In [ ]:
# Map values using a dict
df['grade'] = df['score'].map({
    88.5: 'B+', 92.0: 'A-', 78.3: 'C+'
})

# Map using a function
df['name_upper'] = df['name'].map(str.upper)

# Replace specific values
df['score'].replace(78.3, 79.0)
df.replace({'name': {'Bob': 'Robert'}})

In [ ]:
df1 = pd.DataFrame({'id':[1,2], 'val':['a','b']})
df2 = pd.DataFrame({'id':[2,3], 'extra':['x','y']})

# Merge (inner by default)
pd.merge(df1, df2, on='id')
pd.merge(df1, df2, on='id', how='left')   # left join
pd.merge(df1, df2, on='id', how='outer')  # full outer

# Concat (stack vertically)
pd.concat([df1, df2], ignore_index=True)

# Concat horizontally (side by side)
pd.concat([df1, df2], axis=1)

In [ ]:
# iterrows → (index, Series)
for idx, row in df.iterrows():
    print(idx, row['name'], row['score'])

# itertuples → namedtuple (faster than iterrows)
for row in df.itertuples():
    print(row.Index, row.name, row.score)

# Prefer vectorized operations instead:
df['score'] * 2        # much faster than looping

In [ ]:
df = pd.DataFrame({'color': ['red', 'blue', 'red']})

pd.get_dummies(df, columns=['color'])

pd.get_dummies(df, columns=['color'], drop_first=True)  # avoid multicollinearity

In [ ]:
df = pd.DataFrame({
    'dept': ['eng', 'eng', 'hr', 'hr'],
    'salary': [90, 95, 60, 65]
})

df.groupby('dept')['salary'].mean()

df.groupby('dept').agg({'salary': ['mean', 'max', 'count']})

     salary
       mean max count
dept
eng    92.5  95     2
hr     62.5  65     2

In [ ]:
df = pd.DataFrame({
    'region': ['N', 'N', 'S', 'S'],
    'product': ['A', 'B', 'A', 'B'],
    'sales': [100, 200, 150, 250]
})

df.pivot_table(
    values='sales',
    index='region',
    columns='product',
    aggfunc='sum',
    fill_value=0
)

product    A    B
region
N        100  200
S        150  250

In [ ]:
# agg: one row per group
df.groupby('dept')['salary'].agg(['mean', 'std', 'count'])

# transform: broadcasts back to original shape
df['salary_zscore'] = df.groupby('dept')['salary'].transform(
    lambda x: (x - x.mean()) / x.std()
)
# Named aggregation (pandas ≥ 0.25)
df.groupby('dept').agg(
    avg_sal=('salary', 'mean'),
    max_sal=('salary', 'max')
)

In [ ]:
s = pd.Series(['  Alice  ', 'bob', 'CHARLIE'])

s.str.strip()            # remove whitespace
s.str.lower()            # lowercase
s.str.upper()            # uppercase
s.str.title()            # Title Case
s.str.contains('li')    # boolean mask
s.str.startswith('A')  # boolean mask
s.str.replace('e', '3') # replace substring
s.str.split(' ')        # split to list
s.str.len()              # length of each string

In [ ]:
# Set a column as index
df.set_index('name')
# Multi-level index
df.set_index(['dept', 'name'])
# Reset index back to default integers
df.reset_index()                    # old index → column
df.reset_index(drop=True)          # discard old index

In [ ]:
df.assign(
    score_pct = df['score'] / 100,
    senior    = df['age'] >= 30,
    label     = lambda x: x['score'].apply(lambda s: 'A' if s > 90 else 'B')
)

In [ ]:
ages = pd.Series([15, 25, 35, 45, 60])
# Equal-width bins
pd.cut(ages, bins=[0, 18, 35, 60], labels=['youth', 'adult', 'senior'])
# Equal-frequency bins (quantiles)
pd.qcut(ages, q=3, labels=['low', 'mid', 'high'])

In [ ]:
df[['age', 'score']].corr()
df[['age', 'score']].cov()

# Pearson is default; Spearman also available
df[['age', 'score']].corr(method='spearman')

In [ ]:
# melt: wide → long
df_wide = pd.DataFrame({'id':[1,2], 'jan':[100,200], 'feb':[150,250]})
df_long = df_wide.melt(id_vars='id', var_name='month', value_name='sales')

# pivot: long → wide
df_long.pivot(index='id', columns='month', values='sales')

# stack / unstack on multi-index
df.stack()
df.unstack()